### ISSUE TITLE
OS X 10.12 minimum

### ISSUE THREAD

**Issue by D-32** [brianmichel/Juice#10]
I'm still running 10.11 (yes, shame on me). 
Just curious, does this only work on 10.12 or could we also add support for 10.11 without much effort?

**Comment by brianmichel** [comment]
hey @D-32 I _think_ this should work on 10.11 (at least I'm not using any APIs specific to 10.12). However, I don't have a 10.11 machine to test on. If you'd like to downgrade the deployment target and give it a go, let me know how it goes!
