### ISSUE TITLE
Current scale style forgotten when Juice set to launch at system start

### ISSUE THREAD

**Issue by sebj** [brianmichel/Juice#12]
Juice seems to forget which scale style I have chosen whenever it starts at login. If I pick 'ASCII Battery', log out, then log back in again, it's back to the default 'Emoji Faces'.

**Comment by brianmichel** [comment]
Ahh yeah, sounds like a bug, I'll try to fix it today!

**Comment by brianmichel** [comment]
Hey @sebj this should be resolved with the latest release, https://github.com/brianmichel/Juice/releases/tag/builds%2Fbeta%2F2016.12.26104640 thanks for the bug!
