### ISSUE TITLE
Windows Version?

### ISSUE THREAD

**Issue by EMLVIRUS** [brianmichel/Juice#14]
Any plan to add a Windows version for this project?

**Comment by brianmichel** [comment]
Unfortunately I don't have a windows computer or image to dev on so at this
time I'm not planning on developing a windows version, sorry 😞

**Comment by EMLVIRUS** [comment]
Actually why not try a virtual machine? And if you'd like to I can help you to test it out.

**Comment by brianmichel** [comment]
Are there free legal ISOs for VM installation? That's what I was referring
to when I said image, I don't own a copy of windows, but if you know of a
good place I can get a free legal copy I'd love to check it out.

**Comment by EMLVIRUS** [comment]
Check out this Chinese site http://itellyou.cn/
Use KMS to activate it in VM so that there won't be legal issues

**Comment by brianmichel** [comment]
@EMLVIRUS sorry this site looks pretty sketchy and unless I have a license key I'm not activating anything. Sorry, I'm closing this issue for now.
