### ISSUE TITLE
Homebrew / Cask

### ISSUE THREAD

**Issue by rpunkfu** [brianmichel/Juice#17]
Hi, this is a really tweak, maybe consider adding it Homebrew? :)

**Comment by brianmichel** [comment]
@rpunkfu sure, do you have docs on how to do that?

**Comment by jakehschwartz** [comment]
@brianmichel Here is their documentation on adding a cask. https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md

**Comment by rpunkfu** [comment]
@brianmichel, sorry I've been busy, link that @jakehschwartz shared is really good for learning how to do that 😊

**Comment by brianmichel** [comment]
Nice, thanks @jakehschwartz and @rpunkfu would either of you be interested in making this contribution? I read through the docs but didn't see that the official maintainer needed to be the cask contributor, is that correct?

**Comment by rpunkfu** [comment]
I don't know, never pushed to cask repo, but I would be happy to help ;)

**Comment by brianmichel** [comment]
@rpunkfu I assigned you to this issue, let me know if you run into any problems!

**Comment by rpunkfu** [comment]
Cool, thanks ;)

**Comment by heylookltsme** [comment]
Hello friends! I came here looking to request the same thing. 😊  If you're cool with it @brianmichel, I'm probably gonna go ahead and do this soon. 👍🏻

**Comment by heylookltsme** [comment]
We did it, you guys! 🎉

**Comment by brianmichel** [comment]
Hell yeah! Thanks Corinne!!!
