### ISSUE TITLE
Can I use juice on mac OS 10.11.6?

### ISSUE THREAD

**Issue by DonaldDai** [brianmichel/Juice#18]
None

**Comment by Flayor** [comment]
You can read this https://github.com/brianmichel/Juice/issues/15

**Comment by Flayor** [comment]
I test this on 10.11.x as soon :)

**Comment by brianmichel** [comment]
Hey @DonaldDai as mentioned on #15 this project support 10.12 and greater as I don't have a development machine to test 10.11.x support on. I am open to folks figuring out what is broken on 10.11.x and creating a pull request to fix it though!

**Comment by DonaldDai** [comment]
Oh! Thank you so much, you are very nice. I’ll check this later.

On 2017年1月1日 +0800 AM12:32, Flayor <notifications@github.com>, wrote:

You can read this #15<https://github.com/brianmichel/Juice/issues/15>

**Comment by DonaldDai** [comment]
I’ve read #15, does that mean juice can’t work on 10.11.6 now?

On 2017年1月1日 +0800 AM12:42, Flayor <notifications@github.com>, wrote:

I test this on 10.11.x as soon :)

**Comment by Flayor** [comment]
I have test on VM machine and no it's doesn't work :(

do you a laptop en 10.11.x ? if yes contact me on contact@flayor.com thks
