### ISSUE TITLE
Emoji doesn't replace current battery indicator!

### ISSUE THREAD

**Issue by Monte9** [brianmichel/Juice#6]
Installed it through the binary release. Although I noticed that the Emoji does not replace the already existing battery indicator!. Is this the intended behaviour? (I assumed it would replace it).

See screenshot for reference:
![screen shot 2016-12-19 at 5 03 43 pm](https://cloud.githubusercontent.com/assets/7840686/21334562/5c42dd72-c60d-11e6-9191-79a3eb1ad8d2.png)

**Comment by brianmichel** [comment]
Hi @Monte9 it is supplementary to the built-in battery indicator. You can turn off the default battery indicator in System Preferences and just leave Juice running!

**Comment by sashamjolnir** [comment]
I turned off default battery indicator in System Preferences and after few hours my mac shut down without any notification! can Juice notice me, something like this?
![2016-12-26 16 35 24](https://cloud.githubusercontent.com/assets/8746547/21477872/58e2d71e-cb89-11e6-98b4-b02291aea0c7.png)
