### ISSUE TITLE
Add option to launch at login

### ISSUE THREAD

**Issue by sebj** [brianmichel/Juice#7]
Would be useful to have a checkbox to let Juice launch at login, as it didn't seem to launch when I checked.

**Comment by brianmichel** [comment]
Yup, totally agreed. I think I can easily add this through the `ServiceManagement` framework!

**Comment by brianmichel** [comment]
Just leaving this here for me later as a reminder. It seems that the `ServiceManagement` framework is no longer the way to go for such thing and something like https://gist.github.com/plapier/f8e1dde1b1624dfbb3e4 should be used instead.

**Comment by brianmichel** [comment]
This is complete and pushed to the latest release!

**Comment by sebj** [comment]
Awesome, thanks! 😃
